### ISSUE TITLE
WMA can't return a zoo object when nrow(wts)==n and x contains na

### ISSUE THREAD

**Issue by mearsdj** [joshuaulrich/TTR#50] opened 2017-08-25 01:12 UTC
It seems like there is an error, or unintended behavior, in WMA in the situation where NROW(wts)==n is true.
That's because:
if( NROW(wts) == n ) { 
275      
276     x <- na.omit(x) 

You remove all na's from the data input and then calculate ma on x.

However, when you then call reclass(ma,x)  after the ma is calculated, ma and x are of different length in the situation where x contained na.  I think that means reclass will never succeed in that situation. Agree? If so, is there a reason for that, or is it just an situation that hasn't come up?

**Comment by joshuaulrich** [comment] 2017-08-25 01:19
Can you please provide a minimal, reproducible example that demonstrates
the behavior?

**Comment by mearsdj** [comment] 2017-08-25 01:35
Thanks for the quick response. Sure:
dts<-seq(as.Date("2017/01/01"),by=1,length.out=105)
d<-zoo(c(NA,NA,NA,NA,NA,1:100),dts)
d2<-WMA(d,n=10,wts=((1:10)/55))
str(d)
str(d2)

**Comment by joshuaulrich** [comment] 2020-08-03 23:37
This is a duplicate of #96 and was fixed in 9fe5cc53e3a63e085f7c67cfe0b5ad691440cbea.

**Closed by joshuaulrich** 2020-08-03 23:37 UTC
