### ISSUE TITLE
Getting Ticker Symbols Broken

### ISSUE THREAD

**Issue by joesixpack** [joshuaulrich/TTR#86] opened 2019-10-19 17:10 UTC
### Description

NASDAQ.com recently redesigned its website which has broken stockSymbols()

### Expected behavior

Returning a list of tickers from NASDAQ.com

### Minimal, reproducible example

```r
stockSymbols()
```

### Session Info

```r
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] TTR_0.23-4           forcats_0.4.0        stringr_1.4.0        dplyr_0.8.3          purrr_0.3.2         
 [6] readr_1.3.1          tidyr_0.8.3          tibble_2.1.3         ggplot2_3.2.1        tidyverse_1.2.1     
[11] jsonlite_1.6         httr_1.4.1           RevoUtils_11.0.3     RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2       cellranger_1.1.0 pillar_1.4.2     compiler_3.5.3   xts_0.11-2       tools_3.5.3     
 [7] zeallot_0.1.0    lubridate_1.7.4  nlme_3.1-139     gtable_0.3.0     lattice_0.20-38  pkgconfig_2.0.2 
[13] rlang_0.4.0      cli_1.1.0        rstudioapi_0.10  curl_3.3         haven_2.1.0      withr_2.1.2     
[19] xml2_1.2.2       generics_0.0.2   vctrs_0.2.0      hms_0.5.0        grid_3.5.3       tidyselect_0.2.5
[25] glue_1.3.1       R6_2.4.0         readxl_1.3.1     modelr_0.1.5     magrittr_1.5     backports_1.1.4 
[31] scales_1.0.0     rvest_0.3.4      assertthat_0.2.1 colorspace_1.4-1 stringi_1.4.3    lazyeval_0.2.2  
[37] munsell_0.5.0    broom_0.5.2      crayon_1.3.4     zoo_1.8-6
```

**Comment by joshuaulrich** [comment] 2019-10-19 17:17
Please read the [contributing guide](https://github.com/joshuaulrich/TTR/blob/master/.github/CONTRIBUTING.md) before opening an issue or pull request. This is a duplicate of #83, which has been fixed and on CRAN for a week or two now. Please upgrade.

**Closed by joshuaulrich** 2019-10-19 17:17 UTC

**Comment by joesixpack** [comment] 2019-10-19 17:19
Sorry, I forgot to search first.  Didn't realize its been that long outstanding.

**Comment by joshuaulrich** [comment] 2019-10-19 17:21
No worries! I thought it had only been a couple weeks, but it turns out it has been nearly a month.  I really lose track of time... it's almost embarrassing.
